module "ecs-jenkins" {
  source = "github.com/riboseinc/terraform-aws-ecs-jenkins"

  jenkins-java-opts = "${var.jenkins-java-opts}"
  env = "${var.env}"
  identifier = "${var.identifier}"
  name = "${var.name}"
  ecs-cluster-id = "${module.ecs.ecs-cluster-id}"
  sg-id = "${module.ecs.sg-id}"
  subnet-primary-id = "${module.ecs.vpc-subnet-primary-id}"
  subnet-secondary-id = "${module.ecs.vpc-subnet-secondary-id}"
  subnet-primary-cidr = "${module.ecs.vpc-subnet-primary-cidr}"
  subnet-secondary-cidr = "${module.ecs.vpc-subnet-secondary-cidr}"
  vpc-id = "${module.ecs.vpc-id}"
  r53-public-zone-id = "${module.ecs.r53-public-zone-id}"
  r53-public-zone-name = "${module.ecs.r53-public-zone-name}"
  r53-internal-zone-id = "${module.ecs.r53-internal-zone-id}"
  r53-internal-zone-name = "${module.ecs.r53-internal-zone-name}"
  ports = "${var.ports}"
  enable-service = "${var.enable-service}"
  mount_point = "${var.mount_point}"
  container_image = "${var.container_image}"
  iam-certificate-arn = "${module.ecs.iam-certificate-arn}"
  ecs-scheduler-role-arn = "${module.ecs.ecs-scheduler-role-arn}"
}
